/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package WaterFilterPackage;

/**
 * 
 * 
 * @author Tyler Hertenstein, Matt Bishop, Alyson Wolford, Charles Sauerland
 * @Version 1.0.0 - 24 April 2014
 */
public class FilterItemTestFrame extends javax.swing.JFrame {

public final FilterItem PAPER         = new FilterItem("Paper", "paper.jpg", "Small", 60 );
public final FilterItem CHARCOAL      = new FilterItem("Charcoal", "charcoal.jpg", "Small", 60 );
public final FilterItem GRASS         = new FilterItem("Grass", "grass.jpg", "Large", 600 );
public final FilterItem COTTONBALL    = new FilterItem("Cottonball", "cottonball.jpg", "Medium", 150 );
public final FilterItem PAPER_TOWEL   = new FilterItem("Paper Towel", "papertowel.jpg", "Small", 100 );
public final FilterItem COFFEE_FILTER = new FilterItem("Coffee Filter", "coffeefilter.jpg", "Small", 20 );
public final FilterItem FINE_GRAVEL   = new FilterItem("Fine Gravel", "finegravel.jpg", "Large", 1700 );
public final FilterItem COARSE_GRAVEL = new FilterItem("Coarse Gravel", "coarsegravel.jpg", "Large", 2500 );
public final FilterItem SAND          = new FilterItem("Sand", "sand.jpg", "Large", 300 );
public final FilterItem LINEN_CLOTH   = new FilterItem("Linen Cloth", "linencloth.jpg", "Small", 90 );
public final FilterItem CHEESE_CLOTH  = new FilterItem("Cheese Cloth", "cheesecloth.jpg", "Large", 400);
public final FilterItem MESH          = new FilterItem("Mesh", "mesh.jpg", "Medium", 150 );
public final FilterItem FLOUR         = new FilterItem("Flour", "flour.jpg", "Medium", 150 );
public final FilterItem CORNMEAL      = new FilterItem("CornMeal", "cornmeal.jpg", "Medium", 250 );
public final FilterItem FEATHERS      = new FilterItem("Feathers", "feather.jpg", "Medium", 120 );  
    
    
    public FilterItem stageOne = new FilterItem();
    /**
     * Creates new form FilterItemTestFrame
     */
    public FilterItemTestFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterChoiceComboBox = new javax.swing.JComboBox();
        inputButton = new javax.swing.JButton();
        itemNameLabel = new javax.swing.JLabel();
        itemDesLabel = new javax.swing.JLabel();
        fileNameLabel = new javax.swing.JLabel();
        poreSizeLabel = new javax.swing.JLabel();
        itemNameValLabel = new javax.swing.JLabel();
        itemDesValLabel = new javax.swing.JLabel();
        fileNameValLabel = new javax.swing.JLabel();
        poreSizeValLabel = new javax.swing.JLabel();
        pointLabel = new javax.swing.JLabel();
        pointValLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filterChoiceComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Charcoal", "Cloth - Cheese", "Cloth - Linen", "Coffee Filter", "Cornmeal", "Cottonball", "Flour", "Grass", "Gravel - Coarse", "Gravel - Fine", "Mesh", "Paper", "Paper Towel", "Sand" }));
        filterChoiceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterChoiceComboBoxActionPerformed(evt);
            }
        });

        inputButton.setText("Submit");
        inputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputButtonActionPerformed(evt);
            }
        });

        itemNameLabel.setText("Item Name:");

        itemDesLabel.setText("Item Description:");

        fileNameLabel.setText("File Name:");

        poreSizeLabel.setText("Pore Size:");

        itemNameValLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        itemDesValLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fileNameValLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        poreSizeValLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pointLabel.setText("Points:");

        pointValLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filterChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(inputButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(itemNameLabel)
                            .addComponent(itemDesLabel)
                            .addComponent(fileNameLabel)
                            .addComponent(poreSizeLabel)
                            .addComponent(pointLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemNameValLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poreSizeValLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fileNameValLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemDesValLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pointValLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputButton))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameLabel)
                    .addComponent(itemNameValLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemDesValLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemDesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fileNameValLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poreSizeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(poreSizeValLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pointLabel)
                    .addComponent(pointValLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterChoiceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterChoiceComboBoxActionPerformed

    }//GEN-LAST:event_filterChoiceComboBoxActionPerformed

    private void inputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputButtonActionPerformed
             if (filterChoiceComboBox.getSelectedIndex() ==  0) stageOne = CHARCOAL;
        else if (filterChoiceComboBox.getSelectedIndex() ==  1) stageOne = CHEESE_CLOTH;
        else if (filterChoiceComboBox.getSelectedIndex() ==  2) stageOne = LINEN_CLOTH;
        else if (filterChoiceComboBox.getSelectedIndex() ==  3) stageOne = COFFEE_FILTER;
        else if (filterChoiceComboBox.getSelectedIndex() ==  4) stageOne = CORNMEAL;
        else if (filterChoiceComboBox.getSelectedIndex() ==  5) stageOne = COTTONBALL;
        else if (filterChoiceComboBox.getSelectedIndex() ==  6) stageOne = FEATHERS;
        else if (filterChoiceComboBox.getSelectedIndex() ==  7) stageOne = FLOUR;
        else if (filterChoiceComboBox.getSelectedIndex() ==  8) stageOne = GRASS;
        else if (filterChoiceComboBox.getSelectedIndex() ==  9) stageOne = COARSE_GRAVEL;
        else if (filterChoiceComboBox.getSelectedIndex() == 10) stageOne = FINE_GRAVEL;
        else if (filterChoiceComboBox.getSelectedIndex() == 11) stageOne = MESH;
        else if (filterChoiceComboBox.getSelectedIndex() == 12) stageOne = PAPER;
        else if (filterChoiceComboBox.getSelectedIndex() == 13) stageOne = PAPER_TOWEL;
        else if (filterChoiceComboBox.getSelectedIndex() == 14) stageOne = SAND;
        
        
        
        
        
        itemNameValLabel.setText("" + stageOne.getItemName());
        fileNameValLabel.setText("" + stageOne.getImageFileName());
        poreSizeValLabel.setText("" + stageOne.getPoreSize());
        pointValLabel.setText("" + stageOne.getPointValue(1));
    }//GEN-LAST:event_inputButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilterItemTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilterItemTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilterItemTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilterItemTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilterItemTestFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JLabel fileNameValLabel;
    private javax.swing.JComboBox filterChoiceComboBox;
    private javax.swing.JButton inputButton;
    private javax.swing.JLabel itemDesLabel;
    private javax.swing.JLabel itemDesValLabel;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JLabel itemNameValLabel;
    private javax.swing.JLabel pointLabel;
    private javax.swing.JLabel pointValLabel;
    private javax.swing.JLabel poreSizeLabel;
    private javax.swing.JLabel poreSizeValLabel;
    // End of variables declaration//GEN-END:variables
}
